### PR TITLE
Added minimal docker packaging

### PR DESCRIPTION
**Pull request by mohsinhijazee**
Minimal Docker packaging with a minimal `Makefile`. Please see the README for details. 
FYI @mikael-lindstrom 

Allows people to use this proxy without node setup at all on their local machines.

### CODE REVIEW

**Review by mikael-lindstrom — APPROVED** [review]
Thank you for the contribution, looks great to me. I'll try to get this published on dockerhub as soon as possible.

**Comment by mikael-lindstrom** [comment]
Added it to DockerHub https://hub.docker.com/r/lindstrom/amazon-elasticsearch-proxy

**Comment by mohsinhijazee** [comment]
@mikael-lindstrom thank you! Now that it is on docker hub, it would be even more accessible.

**Comment by mikael-lindstrom** [comment]
Thank you for the contribution 🥇

**Pull request merged**
